-- 014_llm_usage.sql
-- One row per LLM call made on behalf of a browser session, so the API can cap
-- how many tokens a session (and the whole site, per day) spends. The chat and
-- the research preview's Agent tab are open to anyone who passes Turnstile, so
-- these caps are what keep the Lumen account from being used as a free LLM.
--
-- budget_key is a hash of the browser's Turnstile cookie, never the cookie itself.
-- Proactive check-ins are server-initiated and are not recorded here.
BEGIN;

CREATE TABLE IF NOT EXISTS chat.llm_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_key TEXT NOT NULL,
    student_id TEXT,
    model TEXT NOT NULL,
    origin TEXT NOT NULL,
    tokens INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_llm_usage_budget_key
    ON chat.llm_usage (budget_key, created_at);

CREATE INDEX IF NOT EXISTS idx_llm_usage_created_at
    ON chat.llm_usage (created_at);

COMMIT;
